site_name: surprise-travel-planning-agent
repo_url: https://github.com/Paraschamoli/surprise-travel-planning-agent
site_url: https://Paraschamoli.github.io/surprise-travel-planning-agent
site_description: Surprise Travel Planning Agent: An AI assistant that designs personalized, surprise travel itineraries based on user preferences, budget, and interests. It suggests destinations, activities, accommodations, and travel routes—turning trips into exciting, hassle-free adventures.
site_author: Paras Chamoli
edit_uri: edit/main/docs/
repo_name: Paraschamoli/surprise-travel-planning-agent
copyright: Maintained by <a href="https://Paraschamoli.com">Paraschamoli</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/surprise_travel_planning_agent"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Paraschamoli/surprise-travel-planning-agent
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/surprise-travel-planning-agent

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
